version: '3.8'

services:
  merchandise-service:
    build: .
    hostname: merchandise-service
    environment:
      DatabaseConnectionOptions__ConnectionString: "Host=host.docker.internal;Port=5428;Database=merchandise-service;Username=postgres;Password=merchandiseServicePassword"
    ports:
      - "8085:80"
    depends_on:
      - merchandise-service-db

  stock-api:
    image: 'ghcr.io/ozon-edu-csharp-2021/stock-api:main'
    hostname: stock-api
    environment:
      DatabaseConnectionOptions__ConnectionString: "Host=host.docker.internal;Port=5427;Database=stock-api;Username=postgres;Password=stockApiPassword"
    ports:
      - "8081:81"
    depends_on:
      - stock-api-db

  supply-service:
    image: 'ghcr.io/ozon-edu-csharp-2021/supply-service:main'
    hostname: supply-service
    environment:
      DbConfiguration__ConnectionString: "Host=host.docker.internal;Port=5426;Database=supply-service;Username=postgres;Password=supplyServicePassword"
    ports:
      - "8082:82"
    depends_on:
      - supply-service-db
    
  emailing-service:
    image: 'ghcr.io/ozon-edu-csharp-2021/emailing-service:main'
    hostname: emailing-service
    ports:
      - "8083:83"

  employees-service:
    image: 'ghcr.io/ozon-edu-csharp-2021/employees-service:main'
    hostname: employees-service
    environment:
      DbConfiguration__ConnectionString: "Host=host.docker.internal;Port=5425;Database=employees-service;Username=postgres;Password=employeeServicePassword"
    ports:
      - "8084:84"
    depends_on:
      - employees-service-db

  merchandise-service-db:
    image: postgres:latest
    ports:
      - "5428:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: merchandiseServicePassword
      POSTGRES_DB: merchandise-service
    command: "-c log_statement=all"

  supply-service-db:
    image: postgres:latest
    ports:
      - "5426:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supplyServicePassword
      POSTGRES_DB: supply-service

  employees-service-db:
    image: postgres:latest
    ports:
      - "5425:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: employeeServicePassword
      POSTGRES_DB: employees-service
    volumes:
      - ./db/employees-service-postgres-db/dbdata:/var/lib/postgresql/data"

  stock-api-db:
    image: postgres:latest
    ports:
      - "5427:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: stockApiPassword
      POSTGRES_DB: stock-api